### PR TITLE
AF2 prev day weather

### PR DESCRIPTION
**Pull request by jasonfic**
All of these updates are getting added to the af2_dags folder with the exception of gcs_utils, which is also being updated with a new utility function (avro_to_gcs)

### CODE REVIEW

**Review by woodjt — CHANGES_REQUESTED** [review]
**GCS loader:**
To do on line 24 of gcs loader still relevant?
Add the env.example for api id
Line 43 - still useful (write a comment or remove)?
And the rest ^ 51/52, 59-61, 66-68, 78-82

**Airflow script:**
Use the GCS_LOADER_PATH env var on line 30
You can use the “DATASET” var on line 37

**Comment by jasonfic** [comment]
Made changes with Jesse's input taken into account

**Review by woodjt — APPROVED** [review]
Nice!

**Comment by jasonfic** [comment]
Final(?) push with input from Jesse and Val taken into account

**Pull request merged**
